version: 2.1
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: cp local.properties.ci local.properties
      - restore_cache:
          key: jars-{{ checksum "build.gradle.kts" }}{{ checksum  "buildSrc/src/main/kotlin/Dependencies.kt" }}-{{ checksum  "sample/build.gradle.kts" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle.kts" }}{{ checksum  "buildSrc/src/main/kotlin/Dependencies.kt" }}-{{ checksum  "sample/build.gradle.kts" }}
      - run:
          name: Check Quality
          command: ./gradlew lint ktlintCheck detekt
      - run:
          name: Build Debug
          command: ./gradlew assembleDebug
      - run:
          name: Run Tests
          command: ./gradlew test
      - store_artifacts:
          path: sample/build/reports
          destination: reports
      - store_test_results:
          path: sample/build/test-results
